name: Run Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    # Strategy configuration should be inside the job definition
    strategy:
      fail-fast: false
      matrix:
        containers: [1]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: cypress-io/github-action@v6
        with:
          node-version: '14'

      - name: Install Cypress
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2

        with:
          start: npm start
          wait-on: 'http://localhost:3000' # Waits for above
          browser: chrome
          headless: true
          record: true
          parallel: true # Runs test in parallel using settings above
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
